{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-14858",
      "ASSIGNER": "secalert@redhat.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-532"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14858",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14858",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2019:3207",
          "name": "RHSA-2019:3207",
          "refsource": "REDHAT",
          "tags": []
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2019:3201",
          "name": "RHSA-2019:3201",
          "refsource": "REDHAT",
          "tags": []
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2019:3202",
          "name": "RHSA-2019:3202",
          "refsource": "REDHAT",
          "tags": []
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2019:3203",
          "name": "RHSA-2019:3203",
          "refsource": "REDHAT",
          "tags": []
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2020:0756",
          "name": "RHSA-2020:0756",
          "refsource": "REDHAT",
          "tags": []
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html",
          "name": "openSUSE-SU-2020:0513",
          "refsource": "SUSE",
          "tags": []
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html",
          "name": "openSUSE-SU-2020:0523",
          "refsource": "SUSE",
          "tags": []
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A vulnerability was found in Ansible engine 2.x up to 2.8 and Ansible tower 3.x up to 3.5. When a module has an argument_spec with sub parameters marked as no_log, passing an invalid parameter name to the module will cause the task to fail before the no_log options in the sub parameters are processed. As a result, data in the sub parameter fields will not be masked and will be displayed if Ansible is run with increased verbosity and present in the module invocation arguments for the task."
        }
      ]
    }
  },
  "configurations": {
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:redhat:ansible_engine:*:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:redhat:ansible_tower:*:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "AV:L/AC:L/Au:N/C:P/I:N/A:N",
        "accessVector": "LOCAL",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "baseScore": 2.1
      },
      "severity": "LOW",
      "exploitabilityScore": 3.9,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2019-10-14T15:15Z",
  "lastModifiedDate": "2019-10-24T23:15Z"
}