{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-1112",
      "ASSIGNER": "secalert@redhat.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-noinfo"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://review.gluster.org/#/c/19899/1..2",
          "name": "https://review.gluster.org/#/c/19899/1..2",
          "refsource": "CONFIRM",
          "tags": [
            "Vendor Advisory"
          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1112",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1112",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://access.redhat.com/articles/3422521",
          "name": "https://access.redhat.com/articles/3422521",
          "refsource": "CONFIRM",
          "tags": [
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:1269",
          "name": "RHSA-2018:1269",
          "refsource": "REDHAT",
          "tags": [
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:1268",
          "name": "RHSA-2018:1268",
          "refsource": "REDHAT",
          "tags": [
            "Third Party Advisory"
          ]
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00035.html",
          "name": "openSUSE-SU-2020:0079",
          "refsource": "SUSE",
          "tags": []
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "glusterfs server before versions 3.10.12, 4.0.2 is vulnerable when using 'auth.allow' option which allows any unauthenticated gluster client to connect from any network to mount gluster storage volumes. NOTE: this vulnerability exists because of a CVE-2018-1088 regression."
        }
      ]
    }
  },
  "configurations": {
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:gluster:glusterfs:*:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:gluster:glusterfs:4.0.2:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "baseScore": 7.5
      },
      "severity": "HIGH",
      "exploitabilityScore": 10,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2018-04-25T12:29Z",
  "lastModifiedDate": "2019-10-09T23:38Z"
}